project:
  name: &projectName cherry

db:
  master:
    dialector: sqlite
    path: test_db.db

jwt:
  issuer: *projectName
  key: MIICXAIBAAKBgQCSNEX4WNWFEaHxws/9Wv5QZK0rIW8/b7QS8tmrMmI7qeHhXehYr9SxceGTUOS/rwPpYm/FJf2bCLJXhQhndAYQyiH3pEUf5UjAD9MBkTGitfxLEiC1tBdlvMMWcQNWjNWwRvHtKLhL8bwGx0WqAPilbudZ6YI/QIGnO4OL2SOvQQIDAQABAoGAAUVWYl1ApeJ3BOdLmt6CnWedSxBZq4nTXTgihObFjH034Gyfi2h5MdL/7KGPC3eAUjQFLV0yLM8mNbU1/dLisUPeEBtRO6/3XM2ZM6a5RP+/T02ouw7Jpuxms/h/xf/H6cVClFlXFi9FXN+vmZyH5fxr1rlfBcnJ+aOCYRqz5tECQQD4Hb2NYGZ2X2Kxk5AoIyNjoJ+Vc/KvBIvcZlL1mtFWwXq7Ix+t09egmAJj2iD+tzQ8LijxfaNBgqelRm9tWSgNAkEAltmMAZ6eOw9d1cg+XRvNzoyhUJ6okpxX1IvuiEF/3nz3wK2S8juy66IUZQEyXkzk2KAcM+Zty0X1e5Erg3TDBQJBAJ+KmCE5VIlXKmIfDboRZicg2JzEUs+hb8GH9l5Bb8yGWsHMgwlGR8fXFupYD5FaAneUAvXNoNV2CxCmau34P10CQEhDcPl5pe0/AEGgSpfJ8P6IieKYDsMlGEIewqcNUZcgoILx45odFSoiG8kDGMDp7xsDIF+QfHpLSjzmn0S7E40CQGrQ563Oq8t9atgsRgSG4f/GIUjLO/djUzpHofaIz6dIqNCD24Dla+2sDRve1HEFuMHzbC8TH8EFH3FkkQUEoEI=
  pub: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSNEX4WNWFEaHxws/9Wv5QZK0rIW8/b7QS8tmrMmI7qeHhXehYr9SxceGTUOS/rwPpYm/FJf2bCLJXhQhndAYQyiH3pEUf5UjAD9MBkTGitfxLEiC1tBdlvMMWcQNWjNWwRvHtKLhL8bwGx0WqAPilbudZ6YI/QIGnO4OL2SOvQQIDAQAB
  expires: 24h
  refreshExpires: 168h