package util

import (
	"github.com/ericnts/log"
	"strings"
	"testing"
)

var enReplacer = strings.NewReplacer("机器人消毒液使用完了，请及时补充", "Please replenish disinfectant",
	"操作完成后，请注意关好箱门！", "Please close the door after operation",
	"紫外消毒中,请远离", "Disinfection in progress, please keep your distance",
	"请核对耗材数量，并点击确认按钮！", "Please press confirm button if the quantity is correct",
	"我要去消毒下一个区域啦，期待下次为您服务！", "I am going to next disinfection area, see you next time",
	"请关好箱门！", "Please close the door",
	"机器人要去补货了，请让宜让", "I am going to replenish, please clear a path",
	"机器人门锁出现异常，请及时处理", "Door lock error, please fix the problem",
	"验证失败，请重试，或点击配送，使用密码进行验证", "Verification failure, please retry. Or press delivery button and verify with the password",
	"使用完了，请及时补充", "Please replenish",
	"请关好箱门", "Please close the door",
	"验证失败，请重试，或点击开门取物，使用密码进行验证", "Verification failure, please retry. Or press Open door button and verify with the password",
	"验证失败，请重试，或点击使用密码进行验证", "Verification failure, please retry, or verify with the password",
	"我接收到查房任务啦，准备出发", "Patrol instruction received, prepare to depart",
	"请通过指纹，刷卡或者选择用户输入密码验证身份", "please use fingerprint, card or user ID to verify identification",
	"我正在等电梯，请大家把电梯口的位置让给我，谢谢！", "please give way, thank you!",
	"请选择配送目的地", "Please choose a destination",
	"呼叫成功，请耐心等待几分钟！", "Roger that, please wait for few minutes",
	"任务已取消", "Task cancelled",
	"请注意避让，谢谢。", "Please keep a distance, thank you",
	"机器人小易已经到达充电桩，开始充电", "Start charging",
	"机器人小易电量低，要回去充电了", "Low Battery, return to charging station",
	"我要开门了，请勿尾随，谨防夹伤", "Door opening, please keep a distance",
	"机器人小易要进电梯了，请让宜让", "I am going into elevator, please give way",
	"机器人小易要出电梯了，请让宜让", "I am going out elevator, please give way",
	"机器人小易要去下一个目的地了，请让宜让", "I am going to next destination, please give way",
	"机器人小易接收到配送任务了，准备出发", "I got a delivery task, ready to depart",
	"机器人小易接收到呼叫任务了，准备出发", "I got an instruction, ready to depart",
	"机器人小易要回去了，请让宜让", "I am returning, please give way",
	"机器人已返回，请安排新任务", "I have returned, please assign new task",
	"请取走您的物品，关好箱门，并点击完成任务", "Please take out your items, close the door , then press task completed button",
	"请放好物品，关好箱门，并选择目的地开始任务", "Please place the items, close the foor , then select destination to start the task",
	"请您关好箱门", "Please close the door",
	"请选择目的地", "Please choose a destination",
	"请关好箱门，再点击开始任务", "Please close the cabin door, then press start task",
	"请关好箱门，再进行下一步", "Please close the cabin door before moving to next step",
	"请取走你的物品，关好箱门，再点击完成任务", "Please take out your items, close the door , then press task completed button",
	"机器人小易已经到达呼叫位置，请您分配任务", "I have arrived, please give instruction",
	"机器人小易已经到达目的地，请您输入密码开门，取走物品", "I have arrived, please enter the password to open the door",
	"我是机器人小易，很高兴跟大家一起乘坐电梯，请大家多多支持我的工作，谢谢", "I am robot Louis. Nice to meet you!",
	"人太多啦，我还是等下一趟吧", "I will wait for the next lift",
	"人太多啦，我还是等下一趟吧", "I will wait for the next lift",
	"机器人小易已经到达目的地，请您输入密码开门，取走物品", "I have arrived, please enter password to open the door",
	"我遇到困难啦，请通知工作人员过来帮忙吧！", "I am stucked, Please call staff to help",
	"机器人要去消毒了，请让宜让", "I am going to disinfection, please give way",
	"机器人要开始消毒了", "Starting disinfection",
	"机器人小易消毒完成，准备回去啦。", "Disinfection complete, ready to depart",
	"急停开关被按下", "Emergency button pressed",
	"请取走退回的物品，并关好箱门", "Pleas take out the returned item, then close the door",
	"有退药", "There are returned drugs",
	"启动扫描失败，请手动选择", "Failed to scan, please select manually",
	"有超时未取", "Overtime items remained",
	"机器人小易已到达，请尽快处理！", "Louis arrived",
	"机器人小易已经到达，很高兴见到你", "Louis arrived, nice to meet you",
	"消毒区域持续有人活动，无法继续消毒，自动到下个区域进行消毒", "Disinfection suspended due to occupied disinfection area. Proceed to next disinfection area",
	"ID不能为空", "ID cannot be empty",
	"RFID已经被其他用户使用", "RFID used by other user",
	"Token失效", "Token invalid",
	"安装包不存在", "Installation package not exist",
	"必须指定机器人ID或者任务组ID", "Must nominate robot ID or task ID",
	"补货任务", "Replenishment task",
	"补货中", "Replenishing",
	"补位任务", "Relocation task",
	"补位中", "Relocating",
	"不存在的任务", "Task not exist",
	"不通知", "No Notification",
	"不支持的任务类型", "Tasks not supported",
	"部门机器人", "Department's robot",
	"操作中", "Operation in progress",
	"测试", "Testing",
	"查房任务", "Patrol task",
	"查询机器人用户信息失败！", "Failed to check user information",
	"查询数据出错", "Wrong inquiry information",
	"查询消毒点位失败", "Disinfection position inquiry failure",
	"查询消毒区域失败", "Disinfection area inquiry failure",
	"常规等待点", "Regular standby position",
	"常规任务点", "Regular task position",
	"超时未取", "Overtime object remained",
	"乘电梯", "Take elevator",
	"充电任务", "Charging Task",
	"充电中", "Charging in progress",
	"出电梯", "Exit elevator",
	"出梯回退点", "Exit elevator return position",
	"出梯任务点", "Exit elevator task position",
	"出梯失败", "Exit elevator failure",
	"创建失败", "Creation failed",
	"创建预约", "Create scheduled task",
	"此机构已注销，请联系管理员", "Department invalid, please contact admin",
	"此机构已注销，请联系管理员!", "Department invalid, please contact admin",
	"错误的地图数据", "Wrong map information",
	"错误的文件地址", "Wrong file address",
	"打开雾化器", "Turn on the nebulizer",
	"打开箱门", "Open the cabin door",
	"打开紫外灯", "Turn on the UV light",
	"大数据服务", "Big Data Service",
	"代理服务", "Assisting service",
	"待接收", "Pending receipt",
	"待配送", "Pending delivery",
	"单机模式", "Offline Mode",
	"到达待接收", "Arrived, pending receipt",
	"到达待配送", "Arrived, pending delivery",
	"到达电梯内的切换地图任务", "Elevator arrived, switching the map",
	"到达楼宇切换点，切换楼宇地图任务", "Building changing position arrived , switching the map",
	"到达通知", "Arrival notification",
	"到达退药点", "Arrived drug return location",
	"到跨楼宇等待位置任务", "Relocate to inter-building docking position",
	"地图数据不能为空", "Map information cannot be empty",
	"等待电梯", "Waiting for elevator",
	"等待任务", "Standby task",
	"等待任务，到达目的地后，进行等待", "Standby task, standby after arriving destination",
	"等待中", "Standing by",
	"等梯重试中", "Trying to wait for elevator again",
	"低", "Low",
	"底盘", "Chassis",
	"电话", "Phone",
	"电话通知", "Phone notification",
	"电量过低", "Low on Battery",
	"电梯按楼层后，等待电梯到达", "After choosing level, wait for the lift",
	"电梯等待点", "Elevator waiting position",
	"电梯等待区域任务", "Elevator waiting area task",
	"电梯调度", "Elevator scheduling",
	"电梯任务，呼叫电梯", "Elevator task, call the elevator",
	"电梯任务，选择楼层", "Elevator task, select floor",
	"调度服务", "Scheduling Service",
	"调度挂起", "Schedule sleeping",
	"调度挂起中", "Scheduling sleeping",
	"调度唤醒", "Schedule awake",
	"调度模式", "Scheduling Mode",
	"调度指定发送之后，等待调度反馈超时", "After scheduling, feedback over-time",
	"调度中", "Scheduling",
	"调节喷雾大小", "Adjust spray size",
	"订单不存在", "Order not exist",
	"定时检测", "Regular checking",
	"定时消毒任务", "Regular disinfection task",
	"对接第三方系统", "Connect third party system",
	"发送失败", "Transmission failure",
	"发送指令错误", "Transmission order error",
	"返程任务", "Return Task",
	"返程中", "Returning",
	"返回充电中", "Returning to charge",
	"范围监控", "Area monitor",
	"放餐失败", "Delivery failure",
	"服务License验证错误", "Service license verification error",
	"服务不存在", "Service not exsist",
	"服务内部错误", "Internal service error",
	"服务响应超时", "Service response over-time",
	"该操作不被支持", "Operation not supported",
	"高", "High",
	"高值耗材", "High-value item",
	"高值耗材相关功能", "High-value item related functions",
	"故障恢复", "Resume normal",
	"故障中", "Error",
	"关闭APP", "Close the APP",
	"关闭底盘", "Turn off the chassis",
	"关闭雾化器", "Close the nebulizer",
	"关闭箱门", "Close the cabin door",
	"关闭紫外灯", "Turn off the UV light",
	"耗材数量不足", "Item Insufficiency",
	"核心服务", "Core Service",
	"后台服务", "Backstage Service",
	"呼叫电梯后，等待电梯到达", "After pressing elevator button, wait for the lift",
	"呼叫任务", "Calling task",
	"呼叫任务中", "Calling task in progress",
	"呼叫优先于返程", "Calling task has higher priority than return task",
	"缓冲任务数量限定已满了，目前已经超量，请稍后再做操作", "Pending list is full, please operate later",
	"缓存的下一个任务是返程，不需要执行返程，请等待调度下发", "Next pending task already is returning, please wait for re-scheduling",
	"缓存队列中已经有充电任务了", "Pending list already have charging task",
	"缓存中还有任务，不允许执行当前任务", "Ad-hoc task is not allowed, sorry",
	"机构ID不能为空", "Department ID cannot be empty",
	"机构不存在！", "Department not exist",
	"机器充电点", "Robot charging station",
	"机器初始点", "Robot starting position",
	"机器人不存在", "Robot not exist",
	"机器人充电中", "Robot is charging",
	"机器人点位不存在", "Robot position not exist",
	"机器人电量不足", "Robot is low on battery",
	"机器人返程中", "Returning",
	"机器人拒绝操作", "Denied operation",
	"机器人离线了", "Robot offline",
	"机器人忙碌：", "Robot is busy:",
	"机器人目的地标识", "Mark robot destination",
	"机器人型号不存在，请检查后重新登录", "Robot model not exist, please retry",
	"机器人型号不匹配，请检查后重新登录", "Robot model not match, please retry",
	"机器人型号配置错误，请检查后重新登录", "Robot model error, please retry",
	"机器人序列号不匹配，请检查后重新登录", "Robot ID not match, please retry",
	"机器人已经被预约了", "Robot reserved",
	"机器人已经有测试任务了", "Robot already have test task",
	"机器人已经有返程任务了", "Robot already have return task",
	"机器人已经在返程待机区了", "Robot already in standby area",
	"机器人用户不存在", "Robot user not exist",
	"机器人用户不存在！", "Robot user not exist!",
	"机器人用户列表导入模板", "Import robot user list into template",
	"机器人在电梯中，不允许取消任务", "Cancel task is not allowed since the robot is in elevator",
	"机器人在计划任务中，不能执行其他任务", "Ad-hoc task is not allowed since the robot is scheduling",
	"机器人状态", "Robot Status",
	"机器人状态已经设置", "Robot status settled",
	"机器自检", "Robot self-diagnosis",
	"即时消毒任务", "Immediate disinfection task",
	"记录配送单号", "Record delivery number",
	"继续任务", "Continue Task",
	"监控定时", "Regular monitor",
	"监控服务", "Monitor service",
	"交通管制等待区域任务", "Traffic control waiting area task",
	"接收通知", "Receive notification",
	"紧急停止", "Emergency stop",
	"进电梯", "Enter elevator",
	"进梯回退点", "Returning position for elevator entering",
	"进梯任务点", "Task position for elevator entering",
	"进梯失败", "Failed to enter elevator",
	"禁止登录", "Login prohibited",
	"开门待接收", "Door opened, waiting for receipt",
	"开始时间不能大于结束时间", "Finishing time must be later than starting time",
	"空的命令", "Empty order",
	"空闲中", "Available",
	"离线", "Offline",
	"连线充电中", "Charging with wire",
	"楼层切换点", "Level switching position",
	"楼宇切换点", "Building switching position",
	"没有操作权限", "No permission for operation",
	"没有可以呼叫的机器人", "No robot available for calling",
	"没有空闲的机器人了", "No robot available",
	"没有权限操作此机器人", "No permission for operating this robot",
	"没有权限访问此接口", "No permission for this interface",
	"模板不存在", "Template not exist",
	"模拟设备", "Analogue equipment",
	"内线电话", "Internal phone",
	"您没有权限修改其他机构用户信息", "Cannot edit other department's user information",
	"排队等待", "Queue and wait",
	"配送计划", "Delivery plan",
	"配送任务", "Delivery task",
	"配送中", "Delivering",
	"启动配送", "Start Delivery",
	"前往消毒中", "Heading to disinfection",
	"请传入客户端地址", "Please enter user address",
	"请求参数错误", "Request parameter error",
	"请求成功", "Request success",
	"请求成功，但有异常", "Request success with abnormal issue",
	"请选择配送点位", "Please select delivery destination",
	"取消", "Cancelled",
	"取消急停", "Cancel emergency stop",
	"取消配送", "Cancel Delivery",
	"取消任务", "Cancel task",
	"取消任务中", "Cancelling task",
	"取消所有任务", "Cancel all tasks",
	"去查房中", "Patroling",
	"去跨楼宇停靠点", "Head to inter-building docking position",
	"去往补货点", "Head to replenish",
	"全部机器人", "All robots",
	"缺少参数", "Parameter missing",
	"缺少查询参数", "Query required parameter missing",
	"缺少任务信息", "Task information missing",
	"认证失败", "Verification failure",
	"任务刚刚到了，等待接收中5分钟之内不接收其他操作", "Task received. Other operations are not allowed in next 5 minutes",
	"任务过期", "Task over-time",
	"任务监控", "Task monitor",
	"任务结束", "Task ended",
	"任务开始", "Start task",
	"任务完成", "Task completed",
	"任务下发", "Task deliver",
	"软急停", "Soft emergency stop",
	"软硬急停", "Soft and hard emergency stop",
	"扫码呼叫", "Scan to call",
	"删除", "Delete",
	"上传日志", "Upload log",
	"声光提醒", "Sound and light notification",
	"释放所有资源", "Release all resources",
	"手动取消", "Manual cancellation",
	"手机终端", "Phone terminal",
	"数据不存在", "Information not exist",
	"数据校验失败", "Information calibration failure",
	"数据重复", "Information duplicated",
	"送餐服务", "Food delivery service",
	"送餐任务", "Food delivery task",
	"推送成功", "Delivery success",
	"退药任务", "Drug return task",
	"退药中", "Drug return task in progress",
	"微信通知", "WeChat notification",
	"未定义", "Undefined",
	"未发现安装包版本信息", "Installation version unfound",
	"未知", "Unknown",
	"未知操作", "Unknown operation",
	"未知方式", "Unknown method",
	"未知类型", "Unknown type",
	"未知模式", "Unknown mode",
	"未知通知类型", "Unknown notification type",
	"未知状态", "Unknown status",
	"文件地址解析失败", "File address expression failure",
	"文件上传失败", "File upload failure",
	"无任务", "No task",
	"无数据可导出", "No data can be exported",
	"无消毒液", "No disinfectant",
	"无效的机构信息", "Invalid department information",
	"无效的密码信息", "Invalid password",
	"无效的请求参数", "Invalid Input",
	"无效的任务信息", "Invalid task information",
	"系统终止", "System terminated",
	"消毒集合里，每个点位的任务类型", "Every task classification in each position in disinfection array",
	"消毒任务点", "Disinfection task position",
	"消毒相关功能", "Disinfection related function",
	"消毒中", "Disinfection in progress",
	"消息确认", "Confirm information",
	"小程序", "Programme",
	"修改", "Edit",
	"医护服务", "Medical care service",
	"医院系统", "Hospital system",
	"移除缓存任务", "Remove pending task",
	"移动冲突等待点中", "Waiting for removing obstacle",
	"移动到楼宇切换点", "Transportation to building switching position",
	"移动电梯等待点中", "Transportation to elevator waiting position",
	"移动任务", "Transportation task",
	"移动任务，出电梯任务移动到电梯口", "Transportation task, move to elevator exit",
	"移动任务，出电梯失败回退点", "Transportation task, returning position for elevator exiting failure",
	"移动任务，进电梯失败回退点", "Transportation task, returning position for elevator entering failure",
	"移动任务，移动到电梯口", "Transportation task, move to elevator entrance",
	"移动任务，移动到电梯内", "Transportation task, move into elevator",
	"移动任务，移动到目的地，未使用", "Transportation task, move into destination, not yet applied",
	"已出电梯", "Exited elevator",
	"已到达冲突等待点", "Arrived conflict waiting position",
	"已到达电梯等待点", "Arrived elevator waiting position",
	"已到达跨楼宇停靠点", "Arrived inter-building docking position",
	"已发送", "Send successful",
	"已接收", "Received",
	"已经到达", "Arrived",
	"已经有指定目的地的呼叫任务了", "Already have calling task for nominated destination",
	"已确认", "Confirmed",
	"异常", "Abnormal",
	"异常取消配送", "Delivery cancelling abnormality",
	"硬急停", "Hard emergency stop",
	"用户密码错误", "Wrong user passwod",
	"用户名或者密码错误!", "Wrong user name or user passwod",
	"用户在其他终端登录", "User logined in other server",
	"邮件", "Mail",
	"有任务正在执行中", "Executing task",
	"有退药", "There are drug to be returned",
	"有新任务", "New task",
	"语音提醒", "Voice prompt",
	"预警服务", "Alarm Service",
	"预警通知", "Alarm notification",
	"预约中", "scheduling",
	"暂停任务", "Task suspend",
	"增加", "Add",
	"账号不存在", "Invalid account",
	"账号不存在！", "Invalid account",
	"账号或密码错误", "Invalid account or password",
	"正常", "Normal",
	"正在下发", "Ordering",
	"正在下发缓存中的任务，请等待", "Ordering pending task, please wait",
	"执行超时", "Execution over-time",
	"执行成功", "Execution success",
	"执行任务", "Execute task",
	"执行失败", "Execution failure",
	"指定的机器人类型没有指定位置的点位", "Nominated robot type do not have specific position",
	"指定机器人", "Nominated Robot",
	"中", "Middle",
	"重启APP", "Restart app",
	"重启底盘", "Restart chasis",
	"资源缺失", "Resources deficiency",
	"自定义包装", "Custom package",
	"最大只能查询五十天数据", "Maximum 50 days data",
	"机器人小易1号的消毒液使用完了，请及时补充。", "Robot No.1 have used up disinfectant, please replenish",
	"6楼护士站取错物品，请及时处理。", "6/F Nurse station took the wrong prodcut",
	"机器人已返回，请安排新任务。", "Robot returned, please give new task",
	"6楼护士站有超时未取的物品，请及时处理。", "6/F Nurse station over-time unattempted",
	"6楼护士站有退回的物品，请及时处理。", "6/F Nurse station have item to be returned",
	"机器人已到达，请你安排任务", "Robot arrived, please give task")

var hkReplacer = strings.NewReplacer("机器人消毒液使用完了，请及时补充", "機械人消毒液用曬啦，麻煩盡快補充",
	"操作完成后，请注意关好箱门！", "用完記得閂好門！",
	"紫外消毒中,请远离", "紫外光消毒緊,麻煩保持距離",
	"请核对耗材数量，并点击确认按钮！", "麻煩對一對物件同數量，然後撳確認！",
	"我要去消毒下一个区域啦，期待下次为您服务！", "我要去消毒下一個區域啦，期待下次為您服務！",
	"请关好箱门！", "麻煩閂好門！",
	"机器人要去补货了，请让宜让", "機械人要去補貨啦，麻煩讓一讓路",
	"机器人门锁出现异常，请及时处理", "機械人門鎖有異常，麻煩盡快處理",
	"验证失败，请重试，或点击配送，使用密码进行验证", "驗證失敗，麻煩重試，或者撳發送，用密碼進行驗證",
	"使用完了，请及时补充", "用完啦，麻煩盡快補充",
	"请关好箱门", "麻煩閂好門",
	"验证失败，请重试，或点击开门取物，使用密码进行验证", "驗證失敗，麻煩重試，或者撳開門取物，用密碼進行驗證",
	"验证失败，请重试，或点击使用密码进行验证", "驗證失敗，麻煩重試，或者撳使用密碼進行驗證",
	"我接收到查房任务啦，准备出发", "我收到巡邏任務啦，準備出發",
	"请通过指纹，刷卡或者选择用户输入密码验证身份", "麻煩用指紋，拍卡或者輸入密碼驗證身份",
	"我正在等电梯，请大家把电梯口的位置让给我，谢谢！", "我宜家等緊𨋢，麻煩大家將𨋢口嘅位置讓俾我，唔該曬！",
	"请选择配送目的地", "麻煩選擇發送目的地",
	"呼叫成功，请耐心等待几分钟！", "呼叫成功，麻煩耐心等幾分鐘！",
	"任务已取消", "任務已經取消",
	"请注意避让，谢谢。", "麻煩讓一讓路，唔該曬。",
	"机器人小易已经到达充电桩，开始充电", "機械人小易已經到咗叉電位，宜家開始叉電",
	"机器人小易电量低，要回去充电了", "機械人小易冇電啦，要返去叉電",
	"我要开门了，请勿尾随，谨防夹伤", "我要開門啦，小心撞到",
	"机器人小易要进电梯了，请让宜让", "機械人小易要入𨋢啦，麻煩讓一讓路",
	"机器人小易要出电梯了，请让宜让", "機械人小易要出𨋢啦，麻煩讓一讓路",
	"机器人小易要去下一个目的地了，请让宜让", "機械人小易要去下一個目的地啦，麻煩讓一讓路",
	"机器人小易接收到配送任务了，准备出发", "機械人小易收到發送任務啦，準備出發",
	"机器人小易接收到呼叫任务了，准备出发", "機械人小易收到呼叫任務啦，準備出發",
	"机器人小易要回去了，请让宜让", "機械人小易要返去啦，麻煩讓一讓路",
	"机器人已返回，请安排新任务", "機械人已經返左去，可以安排新任務",
	"请取走您的物品，关好箱门，并点击完成任务", "麻煩拎走您嘅物品，閂好門，撳完成任務",
	"请放好物品，关好箱门，并选择目的地开始任务", "麻煩擺好物品，閂好門，然後揀目的地開始任務",
	"请您关好箱门", "麻煩閂好門",
	"请选择目的地", "麻煩揀目的地",
	"请关好箱门，再点击开始任务", "麻煩閂好門，再撳開始任務",
	"请关好箱门，再进行下一步", "麻煩閂好門，再進行下一步",
	"请取走你的物品，关好箱门，再点击完成任务", "麻煩拎走你嘅物品，閂好門，再撳完成任務",
	"机器人小易已经到达呼叫位置，请您分配任务", "機械人小易已經到達呼叫位置，麻煩您分配任務",
	"机器人小易已经到达目的地，请您输入密码开门，取走物品", "機械人小易已經到達目的地，麻煩您輸入密碼開門，拎走物品",
	"我是机器人小易，很高兴跟大家一起乘坐电梯，请大家多多支持我的工作，谢谢", "我係機械人小易，好高興同大家一齊坐𨋢，麻煩大家多多支持，多謝",
	"人太多啦，我还是等下一趟吧", "人太多啦，我都係等下一轉啦",
	"人太多啦，我还是等下一趟吧", "人太多啦，我都係等下一轉啦",
	"机器人小易已经到达目的地，请您输入密码开门，取走物品", "機械人小易已經到達目的地，麻煩您輸入密碼開門，拎走物品",
	"我遇到困难啦，请通知工作人员过来帮忙吧！", "我遇到困難，麻煩叫工作人員嚟幫手！",
	"机器人要去消毒了，请让宜让", "機械人要去消毒啦，麻煩讓一讓路",
	"机器人要开始消毒了", "機械人要開始消毒啦",
	"机器人小易消毒完成，准备回去啦。", "機械人小易消毒完成，準備返去啦。",
	"急停开关被按下", "急停掣已經被按下",
	"请取走退回的物品，并关好箱门", "麻煩拎走退返嘅物品，然後閂好門",
	"有退药", "有退翻嘅藥物",
	"启动扫描失败，请手动选择", "啟動掃描失敗，麻煩手動選擇",
	"有超时未取", "有超時未取物件",
	"机器人小易已到达，请尽快处理！", "機械人小易到咗啦，麻煩儘快處理！",
	"机器人小易已经到达，很高兴见到你", "機械人小易到咗啦，好開心見到你",
	"消毒区域持续有人活动，无法继续消毒，自动到下个区域进行消毒", "消毒區域持續有人活動，無法進行消毒，自動去下個區域繼續消毒",
	"ID不能为空", "ID不能為空",
	"RFID已经被其他用户使用", "RFID已經被其他用戶使用",
	"Token失效", "Token失效",
	"安装包不存在", "安裝包不存在",
	"必须指定机器人ID或者任务组ID", "必須指定機器人ID或者任務組ID",
	"补货任务", "補貨任務",
	"补货中", "補貨中",
	"补位任务", "補位任務",
	"补位中", "補位中",
	"不存在的任务", "不存在的任務",
	"不通知", "不通知",
	"不支持的任务类型", "不支持的任務類型",
	"部门机器人", "部門機器人",
	"操作中", "操作中",
	"测试", "測試",
	"查房任务", "查房任務",
	"查询机器人用户信息失败！", "查詢機器人使用者資訊失敗！",
	"查询数据出错", "查詢資料出錯",
	"查询消毒点位失败", "查詢消毒點位失敗",
	"查询消毒区域失败", "查詢消毒區域失敗",
	"常规等待点", "常規等待點",
	"常规任务点", "常規任務點",
	"超时未取", "超時未取",
	"乘电梯", "乘電梯",
	"充电任务", "充電任務",
	"充电中", "充電中",
	"出电梯", "出電梯",
	"出梯回退点", "出梯回退點",
	"出梯任务点", "出梯任務點",
	"出梯失败", "出梯失敗",
	"创建失败", "創建失敗",
	"创建预约", "創建預約",
	"此机构已注销，请联系管理员", "此機構已註銷，請聯繫管理員",
	"此机构已注销，请联系管理员!", "此機構已註銷，請聯繫管理員!",
	"错误的地图数据", "錯誤的地圖資料",
	"错误的文件地址", "錯誤的檔位址",
	"打开雾化器", "打開霧化器",
	"打开箱门", "打開箱門",
	"打开紫外灯", "打開紫外燈",
	"大数据服务", "大資料服務",
	"代理服务", "代理服務",
	"待接收", "待接收",
	"待配送", "待配送",
	"单机模式", "單機模式",
	"到达待接收", "到達待接收",
	"到达待配送", "到達待配送",
	"到达电梯内的切换地图任务", "到達電梯內的切換地圖任務",
	"到达楼宇切换点，切换楼宇地图任务", "到達樓宇切換點，切換樓宇地圖任務",
	"到达通知", "到達通知",
	"到达退药点", "到達退藥點",
	"到跨楼宇等待位置任务", "到跨樓宇等待位置任務",
	"地图数据不能为空", "地圖資料不能為空",
	"等待电梯", "等待電梯",
	"等待任务", "等待任務",
	"等待任务，到达目的地后，进行等待", "等待任務，到達目的地後，進行等待",
	"等待中", "等待中",
	"等梯重试中", "等梯重試中",
	"低", "低",
	"底盘", "底盤",
	"电话", "電話",
	"电话通知", "電話通知",
	"电量过低", "電量過低",
	"电梯按楼层后，等待电梯到达", "電梯按樓層後，等待電梯到達",
	"电梯等待点", "電梯等待點",
	"电梯等待区域任务", "電梯等待區域任務",
	"电梯调度", "電梯調度",
	"电梯任务，呼叫电梯", "電梯任務，呼叫電梯",
	"电梯任务，选择楼层", "電梯任務，選擇樓層",
	"调度服务", "調度服務",
	"调度挂起", "調度掛起",
	"调度挂起中", "調度掛起中",
	"调度唤醒", "調度喚醒",
	"调度模式", "調度模式",
	"调度指定发送之后，等待调度反馈超时", "調度指定發送之後，等待調度回饋超時",
	"调度中", "調度中",
	"调节喷雾大小", "調節噴霧大小",
	"订单不存在", "訂單不存在",
	"定时检测", "定時檢測",
	"定时消毒任务", "定時消毒任務",
	"对接第三方系统", "對接協力廠商系統",
	"发送失败", "發送失敗",
	"发送指令错误", "發送指令錯誤",
	"返程任务", "返程任務",
	"返程中", "返程中",
	"返回充电中", "返回充電中",
	"范围监控", "範圍監控",
	"放餐失败", "放餐失敗",
	"服务License验证错误", "服務License驗證錯誤",
	"服务不存在", "服務不存在",
	"服务内部错误", "服務內部錯誤",
	"服务响应超时", "服務回應超時",
	"该操作不被支持", "該操作不被支援",
	"高", "高",
	"高值耗材", "高值耗材",
	"高值耗材相关功能", "高值耗材相關功能",
	"故障恢复", "故障恢復",
	"故障中", "故障中",
	"关闭APP", "關閉APP",
	"关闭底盘", "關閉底盤",
	"关闭雾化器", "關閉霧化器",
	"关闭箱门", "關閉箱門",
	"关闭紫外灯", "關閉紫外燈",
	"耗材数量不足", "耗材數量不足",
	"核心服务", "核心服務",
	"后台服务", "後臺服務",
	"呼叫电梯后，等待电梯到达", "呼叫電梯後，等待電梯到達",
	"呼叫任务", "呼叫任務",
	"呼叫任务中", "呼叫任務中",
	"呼叫优先于返程", "呼叫優先于返程",
	"缓冲任务数量限定已满了，目前已经超量，请稍后再做操作", "緩衝任務數量限定已滿了，目前已經超量，請稍後再做操作",
	"缓存的下一个任务是返程，不需要执行返程，请等待调度下发", "緩存的下一個任務是返程，不需要執行返程，請等待調度下發",
	"缓存队列中已经有充电任务了", "緩存佇列中已經有充電任務了",
	"缓存中还有任务，不允许执行当前任务", "緩存中還有任務，不允許執行當前任務",
	"机构ID不能为空", "機構ID不能為空",
	"机构不存在！", "機構不存在！",
	"机器充电点", "機器充電點",
	"机器初始点", "機器初始點",
	"机器人不存在", "機器人不存在",
	"机器人充电中", "機器人充電中",
	"机器人点位不存在", "機器人點位不存在",
	"机器人电量不足", "機器人電量不足",
	"机器人返程中", "機器人返程中",
	"机器人拒绝操作", "機器人拒絕操作",
	"机器人离线了", "機器人離線了",
	"机器人忙碌：", "機器人忙碌：",
	"机器人目的地标识", "機器人目的地標識",
	"机器人型号不存在，请检查后重新登录", "機器人型號不存在，請檢查後重新登錄",
	"机器人型号不匹配，请检查后重新登录", "機器人型號不匹配，請檢查後重新登錄",
	"机器人型号配置错误，请检查后重新登录", "機器人型號配置錯誤，請檢查後重新登錄",
	"机器人序列号不匹配，请检查后重新登录", "機器人序號不匹配，請檢查後重新登錄",
	"机器人已经被预约了", "機器人已經被預約了",
	"机器人已经有测试任务了", "機器人已經有測試任務了",
	"机器人已经有返程任务了", "機器人已經有返程任務了",
	"机器人已经在返程待机区了", "機器人已經在返程待機區了",
	"机器人用户不存在", "機器人用戶不存在",
	"机器人用户不存在！", "機器人用戶不存在！",
	"机器人用户列表导入模板", "機器人使用者清單導入範本",
	"机器人在电梯中，不允许取消任务", "機器人在電梯中，不允許取消任務",
	"机器人在计划任务中，不能执行其他任务", "機器人在計畫任務中，不能執行其他任務",
	"机器人状态", "機器人狀態",
	"机器人状态已经设置", "機器人狀態已經設置",
	"机器自检", "機器自檢",
	"即时消毒任务", "即時消毒任務",
	"记录配送单号", "記錄配送單號",
	"继续任务", "繼續任務",
	"监控定时", "監控定時",
	"监控服务", "監控服務",
	"交通管制等待区域任务", "交通管制等待區域任務",
	"接收通知", "接收通知",
	"紧急停止", "緊急停止",
	"进电梯", "進電梯",
	"进梯回退点", "進梯回退點",
	"进梯任务点", "進梯任務點",
	"进梯失败", "進梯失敗",
	"禁止登录", "禁止登錄",
	"开门待接收", "開門待接收",
	"开始时间不能大于结束时间", "開始時間不能大於結束時間",
	"空的命令", "空的命令",
	"空闲中", "空閒中",
	"离线", "離線",
	"连线充电中", "連線充電中",
	"楼层切换点", "樓層切換點",
	"楼宇切换点", "樓宇切換點",
	"没有操作权限", "沒有操作許可權",
	"没有可以呼叫的机器人", "沒有可以呼叫的機器人",
	"没有空闲的机器人了", "沒有空閒的機器人了",
	"没有权限操作此机器人", "沒有許可權操作此機器人",
	"没有权限访问此接口", "沒有許可權訪問此介面",
	"模板不存在", "範本不存在",
	"模拟设备", "類比設備",
	"内线电话", "內線電話",
	"您没有权限修改其他机构用户信息", "您沒有許可權修改其他機構使用者資訊",
	"排队等待", "排隊等待",
	"配送计划", "配送計畫",
	"配送任务", "配送任務",
	"配送中", "配送中",
	"启动配送", "啟動配送",
	"前往消毒中", "前往消毒中",
	"请传入客户端地址", "請傳入用戶端地址",
	"请求参数错误", "請求參數錯誤",
	"请求成功", "請求成功",
	"请求成功，但有异常", "請求成功，但有異常",
	"请选择配送点位", "請選擇配送點位",
	"取消", "取消",
	"取消急停", "取消急停",
	"取消配送", "取消配送",
	"取消任务", "取消任務",
	"取消任务中", "取消任務中",
	"取消所有任务", "取消所有任務",
	"去查房中", "去查房中",
	"去跨楼宇停靠点", "去跨樓宇停靠點",
	"去往补货点", "去往補貨點",
	"全部机器人", "全部機器人",
	"缺少参数", "缺少參數",
	"缺少查询参数", "缺少查詢參數",
	"缺少任务信息", "缺少任務資訊",
	"认证失败", "認證失敗",
	"任务刚刚到了，等待接收中5分钟之内不接收其他操作", "任務剛剛到了，等待接收中5分鐘之內不接收其他操作",
	"任务过期", "任務過期",
	"任务监控", "任務監控",
	"任务结束", "任務結束",
	"任务开始", "任務開始",
	"任务完成", "任務完成",
	"任务下发", "任務下發",
	"软急停", "軟急停",
	"软硬急停", "軟硬急停",
	"扫码呼叫", "掃碼呼叫",
	"删除", "刪除",
	"上传日志", "上傳日誌",
	"声光提醒", "聲光提醒",
	"释放所有资源", "釋放所有資源",
	"手动取消", "手動取消",
	"手机终端", "手機終端",
	"数据不存在", "資料不存在",
	"数据校验失败", "資料校驗失敗",
	"数据重复", "資料重複",
	"送餐服务", "送餐服務",
	"送餐任务", "送餐任務",
	"推送成功", "推送成功",
	"退药任务", "退藥任務",
	"退药中", "退藥中",
	"微信通知", "微信通知",
	"未定义", "未定義",
	"未发现安装包版本信息", "未發現安裝包版本資訊",
	"未知", "未知",
	"未知操作", "未知操作",
	"未知方式", "未知方式",
	"未知类型", "未知類型",
	"未知模式", "未知模式",
	"未知通知类型", "未知通知類型",
	"未知状态", "未知狀態",
	"文件地址解析失败", "檔地址解析失敗",
	"文件上传失败", "檔上傳失敗",
	"无任务", "無任務",
	"无数据可导出", "無數據可匯出",
	"无消毒液", "無消毒液",
	"无效的机构信息", "無效的機構資訊",
	"无效的密码信息", "無效的密碼資訊",
	"无效的请求参数", "無效的請求參數",
	"无效的任务信息", "無效的任務資訊",
	"系统终止", "系統終止",
	"消毒集合里，每个点位的任务类型", "消毒集合裡，每個點位元的任務類型",
	"消毒任务点", "消毒任務點",
	"消毒相关功能", "消毒相關功能",
	"消毒中", "消毒中",
	"消息确认", "消息確認",
	"小程序", "小程式",
	"修改", "修改",
	"医护服务", "醫護服務",
	"医院系统", "醫院系統",
	"移除缓存任务", "移除緩存任務",
	"移动冲突等待点中", "移動衝突等待點中",
	"移动到楼宇切换点", "移動到樓宇切換點",
	"移动电梯等待点中", "移動電梯等待點中",
	"移动任务", "移動任務",
	"移动任务，出电梯任务移动到电梯口", "移動任務，出電梯任務移動到電梯口",
	"移动任务，出电梯失败回退点", "移動任務，出電梯失敗回退點",
	"移动任务，进电梯失败回退点", "移動任務，進電梯失敗回退點",
	"移动任务，移动到电梯口", "移動任務，移動到電梯口",
	"移动任务，移动到电梯内", "移動任務，移動到電梯內",
	"移动任务，移动到目的地，未使用", "移動任務，移動到目的地，未使用",
	"已出电梯", "已出電梯",
	"已到达冲突等待点", "已到達衝突等待點",
	"已到达电梯等待点", "已到達電梯等待點",
	"已到达跨楼宇停靠点", "已到達跨樓宇停靠點",
	"已发送", "已發送",
	"已接收", "已接收",
	"已经到达", "已經到達",
	"已经有指定目的地的呼叫任务了", "已經有指定目的地的呼叫任務了",
	"已确认", "已確認",
	"异常", "異常",
	"异常取消配送", "異常取消配送",
	"硬急停", "硬急停",
	"用户密码错误", "使用者密碼錯誤",
	"用户名或者密码错误!", "用戶名或者密碼錯誤!",
	"用户在其他终端登录", "使用者在其他終端登錄",
	"邮件", "郵件",
	"有任务正在执行中", "有任務正在執行中",
	"有退药", "有退藥",
	"有新任务", "有新任務",
	"语音提醒", "語音提醒",
	"预警服务", "預警服務",
	"预警通知", "預警通知",
	"预约中", "預約中",
	"暂停任务", "暫停任務",
	"增加", "增加",
	"账号不存在", "帳號不存在",
	"账号不存在！", "帳號不存在！",
	"账号或密码错误", "帳號或密碼錯誤",
	"正常", "正常",
	"正在下发", "正在下發",
	"正在下发缓存中的任务，请等待", "正在下發緩存中的任務，請等待",
	"执行超时", "執行超時",
	"执行成功", "執行成功",
	"执行任务", "執行任務",
	"执行失败", "執行失敗",
	"指定的机器人类型没有指定位置的点位", "指定的機器人類型沒有指定位置的點位",
	"指定机器人", "指定機器人",
	"中", "中",
	"重启APP", "重啟APP",
	"重启底盘", "重啟底盤",
	"资源缺失", "資源缺失",
	"自定义包装", "自訂包裝",
	"最大只能查询五十天数据", "最大只能查詢五十天數據",
	"机器人小易1号的消毒液使用完了，请及时补充。", "機器人小易1號的消毒液使用完了，請及時補充。",
	"6楼护士站取错物品，请及时处理。", "6樓護士站取錯物品，請及時處理。",
	"机器人已返回，请安排新任务。", "機器人已返回，請安排新任務。",
	"6楼护士站有超时未取的物品，请及时处理。", "6樓護士站有超時未取的物品，請及時處理。",
	"6楼护士站有退回的物品，请及时处理。", "6樓護士站有退回的物品，請及時處理。",
	"机器人已到达，请你安排任务", "機器人已到達，請你安排任務")

func TestReplace(t *testing.T) {
	str := "\"accountInvalid\": \"账号或密码错误\",\n    \"officeDeleted\": \"此机构已注销，请联系管理员\",\n    \"robotChassisInvalid\": \"机器人序列号不匹配，请检查后重新登录\",\n    \"robotModelInvalid\": \"机器人型号配置错误，请检查后重新登录\",\n    \"robotChassisNotFound\": \"机器人型号不存在，请检查后重新登录\",\n    \"robotChassisNotEqual\": \"机器人型号不匹配，请检查后重新登录\",\n    \"passwordInvalid\": \"无效的密码信息\",\n    \"disinfectAreaNotFound\": \"消毒区域或点位不存在\",\n    \"disinfectTaskRepeat\": \"任务名称或者开始时间重复\",\n    \"disinfectTaskSaveFailed\": \"消毒任务保存失败\",\n    \"disinfectTaskNotFound\": \"定时消毒任务不存在\",\n    \"fileUrlInvalid\": \"文件地址解析失败\",\n    \"fileUrlMistake\": \"错误的文件地址\",\n    \"mapEmpty\": \"地图数据不能为空\",\n    \"mapMistake\": \"错误的地图数据\",\n    \"robotNotFound\": \"机器人不存在\",\n    \"robotModelNotFound\": \"该机构下未查询到可用的机型\",\n    \"noRobotForCall\": \"没有可以呼叫的机器人\",\n    \"consumableNotEnough\": \"耗材数量不足\",\n    \"robotUserNotFound\": \"机器人用户不存在\",\n    \"endBeforeStartTime\": \"开始时间不能大于结束时间\",\n    \"robotOpPermission\": \"没有权限操作此机器人\",\n    \"opInvalid\": \"该操作不被支持\",\n    \"max50Day\": \"最大只能查询五十天的数据\""
	res := hkReplacer.Replace(str)
	log.Infof("\n%s\n", res)

	res = enReplacer.Replace(str)
	log.Infof("\n%s\n", res)
}

func TestCheckPWD(t *testing.T) {
	type args struct {
		pwd []byte
		new []byte
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		{
			name: "case1",
			args: args{
				pwd: []byte("$2a$10$Us7K8oMR5GVsAmsW/X7hCOU88eGUXbzoRCt456/nTaG4z4yxSPClK"),
				new: []byte("1234admin"),
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := CheckPWD(tt.args.pwd, tt.args.new); (err != nil) != tt.wantErr {
				t.Errorf("CheckPWD() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
